apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector: 
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  sessionAffinity: ClientIP
