name: 'Install Dependencies'
description: 'Installs dependencies and updates node modules cache'

runs:
  using: "composite"
  steps:
  - name: cache all node_modules
    id: cache-modules
    uses: actions/cache@v2
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-v1-node_modules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/*') }}-${{ hashFiles('plugins/*') }}
  - name: find location of global yarn cache
    id: yarn-cache
    run: echo "::set-output name=dir::$(yarn cache dir)"
    shell: bash
  - name: Cache global yarn cache
    uses: actions/cache@v2
    with:
      path: ${{ steps.yarn-cache.outputs.dir }}
      key: ${{ runner.os }}-v1-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/*') }}-${{ hashFiles('plugins/*') }}
  - name: Install Dependencies
    run: |
      if echo ${{ steps.cache-modules.outputs.cache-hit }} | grep -c "true"
      then
        echo "Cache hit - skipping dependency installation"
      else
        yarn install --frozen-lockfile
      fi
    shell: bash



