name: 'Install Dependencies'
description: 'Installs dependencies and updates node modules cache'

runs:
  using: "composite"
  steps:
  - name: cache all node_modules
    id: cache-modules
    uses: actions/cache@v2.1.7
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-v2-node_modules-${{ hashfiles('**/package.json') }}-${{ hashFiles('**/packages/app/**') }}-${{ hashFiles('**/app-config.*.yaml') }}
  - name: Cache Cypress
    id: cache-cypress
    uses: actions/cache@v2.1.7
    with:
      path: ~/.cache/Cypress
      key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}
  - name: find location of global yarn cache
    id: yarn-cache
    run: echo "::set-output name=dir::$(yarn cache dir)"
    shell: bash
  - name: Cache global yarn cache
    id: cache-global-yarn
    uses: actions/cache@v2.1.7
    with:
      path: ${{ steps.yarn-cache.outputs.dir }}
      key: ${{ runner.os }}-v2-yarn-${{ hashfiles('**/package.json') }}-${{ hashFiles('**/packages/app/**') }}-${{ hashFiles('**/app-config.*.yaml') }}
  - name: Install Dependencies
    run: |
      if [[ "${{ steps.cache-modules.outputs.cache-hit }}" == "true" ]] && \
      [[ "${{ steps.cache-cypress.outputs.cache-hit }}" == "true" ]] && \
      [[ "${{ steps.cache-global-yarn.outputs.cache-hit }}" == "true" ]]; then
        echo "Cache hit - skipping dependency installation"
      else
        yarn install --frozen-lockfile
      fi
    shell: bash
