name: 'Browser tests'
description: 'Runs browser test using Cypress'
inputs:
  browser-name:
    description: 'Name of browser to run tests'
    required: true
  build-artifacts:
    description: 'Name of file containing build artifacts'
    default: 'build'
    required: false

runs:
  using: "composite"
  steps:
  - run: |
      if [[ ${{ inputs.browser-name == 'edge' }} ]]; then
        sudo apt-get update && export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        sudo rm microsoft.gpg
        sudo apt-get update && sudo apt-get install microsoft-edge-stable
      fi
    shell: bash
  - name: Cypress run
    id: test
    uses: cypress-io/github-action@v3
    with:
      browser: ${{ inputs.browser-name }}
      install: false
      project: ./packages/app
      command: yarn run test:e2e:ci:${{ inputs.browser-name }}
      working-directory: ./packages/app
  - name: Upload Screenshots of failed tests
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.browser-name }}
      path: packages/app/cypress/screenshots
      retention-days: 5
      if-no-files-found: ignore