apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      annotations:
        namespace: lighthouse-bandicoot-dev
    spec:
      securityContext:
        null
      containers:
        - name: backend
          securityContext:
            null
          image: ""
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 7007
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
          command: ["/bin/sh"]
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config
            mountPath: /etc/config
          - name: gh-secrets
            mountPath: /etc/env
            readOnly: true
          envFrom:
          - configMapRef:
              name: configmap
          - secretRef:
              name: gh-secrets
          - secretRef:
              name: postgres-secrets
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
        - name: logger
          image: "busybox"
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              while ! tail -f /var/log/backend.log; do sleep 1 ; done &&
              tail -f /var/log/backend.log 
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
      volumes:
      - name: varlog
        emptyDir: {}
      - name: config
        configMap:
          name: configmap
      - name: gh-secrets
        secret:
          secretName: gh-secrets
      - name: postgres
        secret:
          secretName: postgres-secrets
