apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - name: backend-port
      port: 7007
      protocol: TCP
      targetPort: 7007
  selector:
    name: backend
