app:
  title: Embark Developer Portal
  baseUrl: https://qa.devportal.name

organization:
  name: Embark

backend:
  baseUrl: https://qa.devportal.name
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://qa.devportal.name
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  cache:
    store: memory
  database:
    client: pg
    connection:
      host: ${QA_POSTGRES_SERVICE_HOST}
      port: ${QA_POSTGRES_SERVICE_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  reading:
    allow:
      # allow reading evss swagger
      - host: www.ebenefits.va.gov

integrations:
  github:
    - host: github.com
      token: ${GH_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # providers: {}
  # see https://backstage.io/docs/tutorials/quickstart-app-auth to know more about enabling auth providers
  environment: qa
  providers:
    github:
      development:
        clientId: ${GH_CLIENT_ID}
        clientSecret: ${GH_CLIENT_SECRET}
        callbackUrl: https://qa.devportal.name/api/auth/github/handler/frame
      qa:
        clientId: ${GH_CLIENT_ID}
        clientSecret: ${GH_CLIENT_SECRET}
        callbackUrl: https://qa.devportal.name/api/auth/github/handler/frame

scaffolder:
  github:
    token: ${GH_TOKEN}
    visibility: public # or 'internal' or 'private'

catalog:
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          apiBaseUrl: https://api.github.com
    visibility: public # or 'internal' or 'private'
  rules:
    - allow: [Component, System, API, Group, User, Template, Location]
  locations:
    # Scans all repos for catalog-info.yaml in department-of-veterans-affairs
    # - type: github-discovery
    # target: https://github.com/department-of-veterans-affairs/lighthouse-*/blob/-/catalog-info.yaml

    #################### EMBARK #########################

    # Embark
    - type: url
      target: https://github.com/department-of-veterans-affairs/lighthouse-embark/blob/main/catalog-info.yaml

    # app component
    - type: url
      target: https://github.com/department-of-veterans-affairs/lighthouse-embark/blob/main/packages/app/catalog-info.yaml

    # backend component
    - type: url
      target: https://github.com/department-of-veterans-affairs/lighthouse-embark/blob/main/packages/backend/catalog-info.yaml

    # feature-flags component
    - type: url
      target: https://github.com/department-of-veterans-affairs/lighthouse-embark/blob/main/plugins/feature-flag-ui/catalog-info.yaml

    # system
    - type: url
      target: https://github.com/department-of-veterans-affairs/lighthouse-embark/blob/main/catalog-info.yaml
