site_name: 'example-docs'
repo_url: 'https://github.com/department-of-veterans-affairs/lighthouse-backstage'

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Running Locally: running-locally.md
  - Backstage Update: backstage-update.md
  - Deploy Local K8s Cluster: local-k8s.md
  - Helm Charts: helm.md
  - Allstar: allstar.md
  - Cypress Troubleshooting: cypress-troubleshooting.md
  - RFCs and decision records:
      - Yarn Zero Install(ADR): zero-install-adr.md
      - Split FE/BE(ADR): split-fe-be-adr.md
      - Cypress e2e Tests(ADR): cypress-e2e-tests-adr.md
      - Ignore Backend Code Coverage: code-cov-adr.md
      - RFC Doc Generator: rfc-doc-generator.md
      - RFC CI/CD Modifications: rfc-ci-cd.md
      - RFC Catalog Import Research: rfc-catalog-import-research.md
      - RFC Node App Logging: rfc-node-app-logging.md
      - RFC Docker Scanning: rfc-docker-scanning.md
      - RFC Enforce Build Performance: rfc-enforce-build-performance.md
      - RFC Linting Rules: rfc-linting.md

plugins:
  - techdocs-core
