site_name: 'example-docs'
repo_url: 'https://github.com/department-of-veterans-affairs/lighthouse-backstage'

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Running Locally: running-locally.md
  - Backstage Update: backstage-update.md
  - RFCs and decision records:
      - RFC Doc Generator: rfc-doc-generator.md
      - Yarn Zero Install(ADR): zero-install-adr.md

plugins:
  - techdocs-core
