site_name: 'example-docs'
repo_url: 'https://github.com/department-of-veterans-affairs/lighthouse-backstage'

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Running Locally: running-locally.md
  - Backstage Update: backstage-update.md
  - Deploy Local K8s Cluster: local-k8s.md
  - Allstar: allstar.md
  - RFCs and decision records:
      - Yarn Zero Install(ADR): zero-install-adr.md
      - Cypress e2e Tests(ADR): cypress-e2e-tests.md
      - RFC Doc Generator: rfc-doc-generator.md
      - RFC CI/CD Modifications: rfc-ci-cd.md
      - RFC Node App Logging: rfc-node-app-logging.md

plugins:
  - techdocs-core
