site_name: 'example-docs'
repo_url: 'https://github.com/department-of-veterans-affairs/lighthouse-backstage'

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Running Locally: running-locally.md

plugins:
  - techdocs-core
