name: Build devcontainer image
description: 'Builds the devcontainer image used for Codespaces'
inputs:
  token:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner  }}
        password: ${{ inputs.token }} # This is not the actual password of the user, just a token
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ github.repository_owner }}/lighthouse-developer-portal/devcontainer
        tags: |
          type=raw, value=latest
    - name: Build and push image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./.devcontainer
        file: ./.devcontainer/base.Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        secrets: |
          "GIT_AUTH_TOKEN=${{ inputs.token }}"