apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.name }}
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.port }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                node packages/backend --config app-config.yaml --config app-config.{{ .Values.DEPLOY_ENV }}.yaml | sed -u -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" >> /var/log/backend.log
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /etc/config
            name: config
          envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-nonprod-configmap"
          - secretRef:
              name: "{{ .Release.Name }}-secrets"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: logger
          image: "busybox"
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              while ! tail -f /var/log/backend.log; do sleep 1 ; done &&
              tail -f /var/log/backend.log 
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: varlog
        emptyDir: {}
      - configMap:
          name: "{{ .Release.Name }}-nonprod-configmap"
        name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
