frontend:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7000
  database:
    connection:
      host: db
      user: postgres
      password: postgres
  cors:
    origin: '*'
    methods: [GET, POST, PUT, DELETE]
    credentials: true
