frontend:
  baseUrl: http://127.0.0.1:3000

backend:
  baseUrl: http://127.0.0.1:7007
  auth:
    keys:
      - secret: '123456'
  database:
    connection:
      host: db
      user: postgres
      password: postgres
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
auth:
  providers:
    github:
      development:
        clientId: '12345'
        clientSecret: '12345'
