apiVersion: v1
kind: Service
metadata:
  name: backstage-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2
    port: 7007
    protocol: TCP
    targetPort: 7007
  selector:
    app: backstage
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}