# Default values for lighthouse-embark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: ghcr.io/department-of-veterans-affairs/lighthouse-embark
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  # For deployment repo this will be hardcoded and updated with Argo, i.e:
  # tag: "sha-6dcd760d389e826b58586cde61f5ead1ca464943"
  tag: "placeholder"

name: backend-port
port: 7007
livenessProbe:
  initialDelaySeconds: 5
  path: /healthcheck
readinessProbe:
  initialDelaySeconds: 5
  path: /healthcheck

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations:

DEPLOY_ENV: "placeholder"
SERVICE_ACCOUNT: "placeholder"

podSecurityContext:
  fsGroup: 1000
service:
  type: ClusterIP
  port: 7007

resources:
  requests:
    cpu: '0.5'
    memory: '500Mi'
  limits:
    cpu: '2'
    memory: '2000Mi'

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
