apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: lighthouse-backstage
  description: The frontend applicaton for lighthouse-backstage
  tags:
    - javascript
    - typescript
    - react
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-backstage/issues
      title: Issues
      icon: alert
    - url: https://department-of-veterans-affairs.github.io/lighthouse-backstage/
      title: Docs
      icon: help
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/department-of-veterans-affairs/lighthouse-backstage
    github.com/project-slug: department-of-veterans-affairs/lighthouse-backstage
spec:
  type: website
  owner: lighthouse-bandicoot
  lifecycle: experimental
  system: lighthouse-backstage
