apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: lighthouse-embark
  description: The frontend application for Embark
  tags:
    - javascript
    - typescript
    - react
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-embark/issues
      title: Issues
      icon: help
    - url: https://department-of-veterans-affairs.github.io/lighthouse-embark/
      title: Docs
      icon: dashboard
    - url: https://backstage.io/
      title: Backstage.io
      icon: web
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: group
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/department-of-veterans-affairs/lighthouse-embark
    github.com/project-slug: department-of-veterans-affairs/lighthouse-embark
spec:
  type: website
  owner: lighthouse-bandicoot
  lifecycle: experimental
  system: embark
