{{- if .Values.nonprod }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.DEPLOY_ENV }}-cm
  labels: 
    {{- include "embark.labels" . | nindent 4 }}
data:
  APP_CONFIG_app_baseUrl: {{ .Values.BASE_URL }}
  APP_CONFIG_backend_baseUrl: {{ .Values.BASE_URL }}
  APP_CONFIG_backend_cors_origin: {{ .Values.BASE_URL }}
  APP_CONFIG_backend_listen_port: "7007"
  AWS_BUCKET_NAME: {{ .Values.AWS_BUCKET_NAME }}
  DOCSERVER_BASE_URL: {{ .Values.DOCSERVER_BASE_URL }}
{{ end }}
