apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.global.DEPLOY_ENV }}-memcached-efs-claim"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
