apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "embark.fullname" . }}-virtualservice
spec:
  hosts:
  - {{ .Values.HOST }}
  gateways:
  - {{ .Values.GATEWAY }}
  http:
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: "{{ .Release.Name }}-backend-service"
        port: 
          number: {{ .Values.virtualService.destination.backend.port }}
  - match:
    route:
    - destination:
        host: "{{ .Release.Name }}-frontend-service"
        port: 
          number: {{ .Values.virtualService.destination.frontend.port }}
