# Default values for lighthouse-embark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 3

secrets:
  DOCKERCONFIGJSON: ${DOCKERCONFIGJSON}
  GH_TOKEN: ${GH_TOKEN}
  BASE_URL: ${BASE_URL}
  HOST: ${HOST}
  GATEWAY: ${GATEWAY}
  GH_CLIENT_ID: ${GH_CLIENT_ID}
  GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
  nonprod: ${nonprod}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  SERVICE_ACCOUNT: $SERVICE_ACCOUNT}
  DOCSERVER_BASE_URL: ${DOCSERVER_BASE_URL}

podAnnotations:
  namespace: lighthouse-bandicoot-dev

service:
  type: ClusterIP

virtualService:
  destination:
    frontend:
      port: 8000
    backend:
      port: 7007

resources:
  requests:
    cpu: '0.1'
    memory: '50Mi'
  limits:
    cpu: '0.2'
    memory: '100Mi'

nodeSelector: {}

tolerations: []

affinity: {}
