name: 'Code Quality'
description: 'Generates score for cognitive complexity and pushes result to Datadog'
outputs:
  score:
    description: "Average Cognitive Complexity Score"
    value: ${{ steps.overall.outputs.average }}

runs:
  using: "composite"
  steps:
  - name: Generate scores
    run: |
      echo "y" | npx code-complexity --format json . > overall-results.json
    shell: bash
  - name: Calculate overall average scores
    id: overall
    run: |
      count=$(jq length overall-results.json)
      sum=$(cat overall-results.json |  jq -n '[inputs | .[] | .score] | reduce .[] as $num (0; .+$num)')
      average=$(echo $sum/$count | bc -l)
      echo ::set-output name=average::$average
    shell: bash
  - name: Print results
    run: |
      echo "Cognitive Complexity Summary"
      printf "Overall Average Complexity Score: %.3f\n" ${{ steps.overall.outputs.average }}
    shell: bash
  - name: Store results
    uses: actions/upload-artifact@v2
    with:
      name: cognitive-complexity-results
      path: |
        overall-results.json

