apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: The backend server for lighthouse-embark.
  tags:
    - javascript
    - node
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-embark/issues
      title: Issues
      icon: help
    - url: https://department-of-veterans-affairs.github.io/lighthouse-embark/
      title: Docs
      icon: dashboard
    - url: https://backstage.io/
      title: Backstage.io
      icon: web
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: slack
  annotations:
    github.com/project-slug: department-of-veterans-affairs/lighthouse-embark/packages/backend
spec:
  type: website
  owner: lighthouse-bandicoot
  lifecycle: experimental
  system: embark-developer-portal
  subcomponentOf: embark-monorepo
  consumesApi:
    - api:default/embark-catalog-api
  dependsOn:
    - resource:default/embark-db
