name: 'Send Deployment Webhook'
description: 'Sends a webhook to the backstage-deployment repo containing the latest commit SHA'
inputs:
  ENV:
    description: 'Flag used to set environment variable overrides'
    required: true
  WEBHOOK_DEPLOY_PAT:
    description: 'PAT for authorization'
    required: true
  MAIN_SHA:
    description: 'The latest SHA for the main branch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send webhook to backstage-deployment repo
      run: |
        curl -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{ inputs.WEBHOOK_DEPLOY_PAT }}" \
        --request POST \
        --data '{ "event_type": "${{ inputs.ENV }}", "client_payload": { "commit_sha": "${{ inputs.MAIN_SHA }}" } }' \
        https://api.github.com/repos/department-of-veterans-affairs/backstage-deployment/dispatches
      shell: bash
