name: 'Deploy Backstage app'
description: 'Deploys Backstage application to an environment using helm'
inputs:
  KUBE_CONFIG: 
    description: 'Kubernetes context'
    required: true
  DOCKERCONFIGJSON:
    description: 'Authentication for pulling from image registry'
    required: true
  GH_TOKEN:  
    description: 'Base64 encoded github token'
    required: true
  GH_CLIENT_ID:
    description: 'OAuth client ID'
    required: true
  GH_CLIENT_SECRET:
    description: 'OAuth client secret'
    required: true
  ENV:
    description: 'Flag used to set environment variable overrides'
    required: true
  POSTGRES_USER:
    description: 'Username for postgres database'
    required: true
  POSTGRES_PASSWORD:
    description: 'Password for postgres database'
    required: true
  POSTGRES_DB:
    description: 'Name of postgres database'
    required: true


runs:
  using: "composite"
  steps:
  - name: Set K8s context
    uses: azure/k8s-set-context@v1
    with:
      method: kubeconfig
      kubeconfig: ${{ inputs.KUBE_CONFIG }}
  - name: Set env overrides 
    id: overrides
    run: |
      echo "::set-output name=nonprod::true"
      if [[ "${{ inputs.ENV }}" == "dev" ]]; then
        echo "::set-output name=BASE_URL::https://dev.devportal.name"
        echo "::set-output name=BACKEND_PORT::7000"
        echo "::set-output name=HOST::dev.devportal.name"
        echo "::set-output name=GATEWAY::istio-system/dev-devportal-name-gateway"
      fi
      if [[ "${{ inputs.ENV }}" == "qa" ]]; then
        echo "::set-output name=BASE_URL::https://qa.devportal.name"
        echo "::set-output name=BACKEND_PORT::7000"
        echo "::set-output name=HOST::qa.devportal.name"
        echo "::set-output name=GATEWAY::istio-system/qa-devportal-name-gateway"
      fi
      if [[ "${{ inputs.ENV }}" == "prod" ]]; then
        echo "::set-output name=nonprod::false"
      fi
    shell: bash
  - name: Create image tag
    id: tag
    run: |
      prefix="sha-"
      prefix+=${{ github.sha }}
      echo "::set-output name=sha::$prefix"
    shell: bash
  - name: Upgrade(or install) helm release
    run: >
      helm upgrade lighthouse-embark-${{ inputs.ENV }} helm/embark/ --debug --values helm/embark/values.yaml 
      --namespace lighthouse-bandicoot-dev --set DOCKERCONFIGJSON=${{ inputs.DOCKERCONFIGJSON }} --set GH_TOKEN=${{ inputs.GH_TOKEN }} 
      --set GH_CLIENT_ID=${{ inputs.GH_CLIENT_ID }} --set GH_CLIENT_SECRET=${{ inputs.GH_CLIENT_SECRET }} 
      --set nonprod=${{ steps.overrides.outputs.nonprod }},backend.nonprod=${{ steps.overrides.outputs.nonprod }},frontend.nonprod=${{ steps.overrides.outputs.nonprod }} 
      --set BASE_URL=${{ steps.overrides.outputs.BASE_URL }} --set HOST=${{ steps.overrides.outputs.HOST }} --set GATEWAY=${{ steps.overrides.outputs.GATEWAY }} --set BACKEND_PORT=7000 
      --set DEPLOY_ENV=${{ inputs.ENV }},backend.DEPLOY_ENV=${{ inputs.ENV }} 
      --set backend.image.tag=${{ steps.tag.outputs.sha }},frontend.image.tag=${{ steps.tag.outputs.sha }} 
      --set POSTGRES_USER=${{ inputs.POSTGRES_USER }},backend.POSTGRES_USER=${{ inputs.POSTGRES_USER }} 
      --set POSTGRES_PASSWORD=${{ inputs.POSTGRES_PASSWORD }},backend.POSTGRES_PASSWORD=${{ inputs.POSTGRES_PASSWORD }} 
      --set POSTGRES_DB=${{ inputs.POSTGRES_DB }},backend.POSTGRES_DB=${{ inputs.POSTGRES_DB }}
      --install --atomic --cleanup-on-fail --history-max 5
    shell: bash
