apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
spec:
  selector:
    name: frontend
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 3000
  sessionAffinity: ClientIP