apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.DEPLOY_ENV }}-backend-service
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
