# Default values for lighthouse-developer-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}

global:
  DEPLOY_ENV: ${DEPLOY_ENV}
  image:
    tag: ${COMMIT_SHA}
  SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
  MEMCACHED_USER: ${MEMCACHED_USER}
  MEMCACHED_PASSWORD: ${MEMCACHED_PASSWORD}

nodeSelector: {}

replicaCount: 1
revisionHistoryLimit: 3

resources:
  requests:
    cpu: '0.5'
    memory: '512Mi'
  limits:
    cpu: '1'
    memory: '1024Mi'

secrets:
  DOCKERCONFIGJSON: ${DOCKERCONFIGJSON}
  BACKEND_SECRET: ${BACKEND_SECRET}
  BASE_URL: ${BASE_URL}
  HOST: ${HOST}
  GATEWAY: ${GATEWAY}
  GH_CLIENT_ID: ${GH_CLIENT_ID}
  GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
  nonprod: ${nonprod}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  DOCSERVER_BASE_URL: ${DOCSERVER_BASE_URL}

service:
  type: ClusterIP

tolerations: []

virtualService:
  destination:
    frontend:
      port: 8000
    backend:
      port: 7007
