name: Browser Tests

# This action was built using the cypress-io/github-action
# @see https://github.com/marketplace/actions/cypress-io
#
# --------------- ARTIFACTS ---------------------
# Any failed tests will use the upload-artifact action to upload any screenshots.
# Each artifact is saved under it's browser type name
# @see https://github.com/actions/upload-artifact
#
# Screenshots are saved to the packages/app/cypress/screenshots folder.

# Runs all tests located within packages/app using Cypress

on:
  push:
    branches: [main, browser-tests]
  pull_request:
    branches: [main]

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./packages/app
          build: yarn run build
          command: yarn run test:e2e:ci
          working-directory: packages/app
        # Upload screenshots as "electron" if tests fail
      - name: Upload Screenshots of failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: electron
          path: packages/app/cypress/screenshots
          retention-days: 5

  browser-tests-chrome:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - uses: cypress-io/github-action@v3
        with:
          browser: chrome
          project: ./packages/app
          build: yarn run build
          command: yarn run test:e2e:ci
          working-directory: packages/app
        # Upload screenshots as "chrome" if tests fail
      - name: Upload Screenshots of failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: chrome
          path: packages/app/cypress/screenshots
          retention-days: 5

  browser-tests-edge:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - uses: cypress-io/github-action@v3
        with:
          browser: edge
          # Increase install time to prevent timeout
          install-command: yarn --frozen-lockfile --network-timeout 1000000000
          project: ./packages/app
          build: yarn run build
          command: yarn run test:e2e:ci
          working-directory: packages/app
        # Upload screenshots as "edge" if tests fail
      - name: Upload Screenshots of failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: edge
          path: packages/app/cypress/screenshots
          retention-days: 5
