name: build-publish-techdocs

on:
  workflow_dispatch:
    inputs:
      entity_kind:
        description: 'Backstage entity kind'
        required: true
        default: 'Component'
      entity_namespace:
        description: 'Backstage entity namespace'
        required: true
        default: 'default'
      entity_name:
        description: 'Backstage entity name'
        required: true
      techdocs_repo_full_name:
        description: 'Repo to pull TechDocs markdown from'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENTITY_NAMESPACE: ${{ github.event.inputs.entity_namespace }}
      ENTITY_KIND: ${{ github.event.inputs.entity_kind }}
      ENTITY_NAME: ${{ github.event.inputs.entity_name }}
      REPO_FULL_NAME: ${{ github.event.inputs.techdocs_repo_full_name }}
    steps:
      - name: Fail if input missing
        if: ${{ !ENTITY_NAMESPACE || !ENTITY_KIND || !ENTITY_NAME || !REPO_FULL_NAME }}
        run: >
          echo "Missing required input. Check what's missing:" &&
          echo "ENTITY_NAMESPACE: ${{ ENTITY_NAMESPACE }} &&
          echo "ENTITY_KIND: ${{ ENTITY_KIND }} &&
          echo "ENTITY_NAME: ${{ ENTITY_NAME }} &&
          echo "TECHDOCS_REPO_FULL_NAME: ${{ REPO_FULL_NAME }} &&
          exit 1
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_FULL_NAME }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          node-version: 14
      - name: Install TechDocs cli
        run: sudo npm install -g @techdocs/cli
      - name: Install mkdocs and mkdocs plugins
        run: pip install mkdocs-techdocs-core==0.*
      - name: Generate docs
        run: techdocs-cli generate --no-docker
      - name: Publish docs
        run: >
          techdocs-cli publish
          --publisher-type awsS3
          --storage-name $TECHDOCS_S3_BUCKET_NAME
          --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME