name: Build Containers

# Confirms that the Frontend and Backend containers are able to build successfully
#
# Both jobs use their own dockerfile to build the docker container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Build Frontend Container
        run: docker build -t backstage-frontend -f Dockerfile.dockerbuild .
  build-backend-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Build Backend Container
        run: docker build -t backstage-backend -f Dockerfile .
