name: Build, test, deploy main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHOULD_DEPLOY: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Transpile typescript
        run: yarn tsc
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test:all
      - name: Build docker image
        run: docker image build -t backstage/staging/runner .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@5c8dff7f31948b22222e5f2aac5a19074dbb9fa4 # pin@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: backstage:latest
      # - name: Login to Heroku Container registry
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: heroku container:login
      # - name: Build and push to Heroku
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: heroku container:push web -a lighthouse-backstage
      # - name: Release to Heroku
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: heroku container:release web -a lighthouse-backstage
