name: Deploy to QA Environment

on:
  push:
    tags:
    - '[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+[0-9]+'
    
jobs:
  deploy-app-qa:
    runs-on: ubuntu-latest
    environment: 
      name: QA
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Get current SHA from Main branch
        id: main
        run: |
          echo "::set-output name=COMMIT_SHA::$(git log -n 1 --format='%H' main)"
      - id: deployment-check
        uses: AminFazlMondo/check-deployed-environment@0248df0facfa270f9cc37a2895ed3411ce648c02 # v1.0.13 
        with:
          environment: 'Development'
          commit_sha: ${{ steps.main.outputs.COMMIT_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.deployment-check.outputs.has_active_deployment == true }}
        run: echo "Something is deployed to Dev using this commit sha"
      - name: Deploy app
        uses: ./.github/actions/deploy-backstage-app
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DOCKERCONFIGJSON: ${{ secrets.DOCKERCONFIGJSON }}
          BACKEND_SECRET: ${{ secrets.BACKEND_SECRET }}
          COMMIT_SHA: ${{ steps.main.outputs.COMMIT_SHA }}
          GH_CLIENT_ID: ${{ secrets.GHA_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GHA_CLIENT_SECRET }}
          ENV: "qa"
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          DOCSERVER_BASE_URL: ${{ secrets.DOCSERVER_BASE_URL }}
          APP_CREDS_YAML: ${{ secrets.APP_CREDS_YAML }}
