name: dispatch-build-publish-techdocs

on:
  push:
    branches:
    - "main"
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-publish-techdocs
          token: ${{ secrets.DISPATCH_BUILD_PUBLISH_TECHDOCS_TOKEN }}
          inputs: >
            {
              "entity_name": "lighthouse-backstage",
              "techdocs_repo_full_name":
                "department-of-veterans-affairs/lighthouse-backstage"
            }
