name: Example CI/CD Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # If you update pre-build-validation.yml then you will need to update the commit hash here
  call-pre-build-validation:
    uses: department-of-veterans-affairs/lighthouse-backstage/.github/workflows/pre-build-validation.yml@a42e0b8b91255dc0b6c59777ca4e33dcc5228633

  build-push-images:
    runs-on: ubuntu-latest
    needs: [call-pre-build-validation]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        type: [backend, frontend]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Build and push image
      uses: ./.github/actions/build-push-images
      with: 
        type: ${{ matrix.type }}
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
