name: Example custom action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  example-custom-action:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      # Using path to same repo works    
      - uses: ./.github/actions/logger
        with: 
          string-to-log: 'This should log in the console'

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        type: [backend, frontend]

    steps:
      - uses: actions/checkout@v2
      - name: Build and push FE 
        if: ${{ matrix.type == 'frontend' }}
        uses: ./.github/actions/build_frontend
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
      - name: Build and push BE 
        if: ${{ matrix.type == 'backend' }}
        uses: ./.github/actions/build_backend
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
