name: Migrate DBs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  migrate-dbs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Migrate DBs
        uses: ./.github/actions/migrate-dbs
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          SRC: 'Qa'
          DEST: 'Dev'