name: Pre-build Validation

on:
  workflow_call:
    secrets:
      SLACK_UID_001:
        description: 'Slack User ID 1'
        required: true
      SLACK_UID_002:
        description: 'Slack User ID 2'
        required: true
      SLACK_UID_003:
        description: 'Slack User ID 3'
        required: true
      SLACK_UID_004:
        description: 'Slack User ID 4'
        required: true
      SLACK_WEBHOOK_URL:
        description: 'Slack Webhook Url to post slack messages'
        required: true
      DATADOG_API_KEY:
        description: 'Datadog API key used to send metrics to Datadog'
        required: true

# Need to consolidate and add unit-tests.yml to this workflow
jobs:
  validate-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/validate-unit-tests
        with:
          SLACK_UID_001: ${{ secrets.SLACK_UID_ABDUSAMAD }}
          SLACK_UID_002: ${{ secrets.SLACK_UID_FOWLER }}
          SLACK_UID_003: ${{ secrets.SLACK_UID_LOVENDAHL }}
          SLACK_UID_004: ${{ secrets.SLACK_UID_LUCKEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  validate-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Run linting
      uses: ./.github/actions/validate-linting

  assess-code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate cognitive complexity results
      id: cognitive-complexity
      uses: ./.github/actions/assess-code-quality
    - name: Send cognitive complexity score to datadog
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
        metrics: |
          - type: "count"
            name: "cognitive.complexity.score"
            value: ${{ steps.cognitive-complexity.outputs.score }}
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"
