name: Pre-build Validation
on:
  workflow_call:
    inputs:
      UNIT_TEST_STATUS:
        type: string
        description: 'Status of unit test workflow run'
        required: true
    secrets:
      SLACK_UID_001:
        description: 'Slack User ID 1'
        required: true
      SLACK_UID_002:
        description: 'Slack User ID 2'
        required: true
      SLACK_UID_003:
        description: 'Slack User ID 3'
        required: true
      SLACK_UID_004:
        description: 'Slack User ID 4'
        required: false
      SLACK_WEBHOOK_URL:
        description: 'Slack Webhook Url to post slack messages'
        required: true
      DATADOG_API_KEY:
        description: 'Datadog API key used to send metrics to Datadog'
        required: true
jobs:
  validate-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-unit-tests
        with:
          UNIT_TEST_STATUS: ${{ inputs.UNIT_TEST_STATUS }}
          SLACK_UID_001: ${{ secrets.SLACK_UID_001 }}
          SLACK_UID_002: ${{ secrets.SLACK_UID_002 }}
          SLACK_UID_003: ${{ secrets.SLACK_UID_003 }}
          SLACK_UID_004: ${{ secrets.SLACK_UID_004 }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  validate-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Run linting
      uses: ./.github/actions/validate-linting
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@2f478ec3b2c8a321d46fca773f6285a447234f6a # v0.7.1
        # input parameters
        with:
          github_access_token: "${{ secrets.WEBHOOK_DEPLOY_PAT }}"
  assess-code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate cognitive complexity results
      id: cognitive-complexity
      uses: ./.github/actions/assess-code-quality
    - name: Send cognitive complexity score to datadog
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
        metrics: |
          - type: "count"
            name: "cognitive.complexity.score"
            value: ${{ steps.cognitive-complexity.outputs.score }}
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"
