name: Build Documentation

# GitHub Action for documentation generation
#
# This action generates documentation for all applications in the catalog using techdocs/cli and mkdocks.
# Docs are added to the ./site folder
#
# The contents of ./site folder are then published to a `gh-pages` branch.
# GitHub pages are then available for viewing at https://department-of-veterans-affairs.github.io/lighthouse-backstage/

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_FULL_NAME }}
      - uses: ./.github/actions/publish_documentation
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
