name: Register plugin
on:
  issues:
    types: [labeled]
  workflow_dispatch:
jobs:
  update-team-access:
    if: (contains(github.event.issue.labels.*.name, 'add-plugin-to-repo') && !contains(github.event.issue.labels.*.name, 'processed')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Register new plugin
        uses: ./.github/actions/register-plugin
        with:
          ISSUE_ID: ${{ github.event.issue.number }}
          TOKEN: ${{ secrets.GHA_TOKEN }}