# From https://github.com/changesets/action#example-workflow
name: Release

on:
  push:
    branches:
      - main
      - changesets
    tags:
      - "v*"
  workflow_dispatch:


env:
  IMAGE_NAME: lighthouse-backstage

jobs:

  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: |
          yarn install --frozen-lockfile && yarn tsc
          yarn build && docker build . -f Dockerfile --tag $IMAGE_NAME/backend --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build frontend image
        run: docker build . -f Dockerfile.dockerbuild --tag $IMAGE_NAME/frontend --label "runnumber=${GITHUB_RUN_ID}"


      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          IMAGE_ID_FRONTEND=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME/frontend
          IMAGE_ID_BACKEND=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME/backend
      
          IMAGE_ID_FRONTEND=$(echo $IMAGE_ID_FRONTEND | tr '[A-Z]' '[a-z]')
          IMAGE_ID_BACKEND=$(echo $IMAGE_ID_BACKEND | tr '[A-Z]' '[a-z]')
          
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID_FRONTEND=$IMAGE_ID_FRONTEND
          echo IMAGE_ID_BACKEND=$IMAGE_ID_BACKEND
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME/frontend $IMAGE_ID_FRONTEND:$VERSION
          docker tag $IMAGE_NAME/backend $IMAGE_ID_BACKEND:$VERSION
          docker push $IMAGE_ID_FRONTEND:$VERSION
          docker push $IMAGE_ID_BACKEND:$VERSION

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Generate changelogs
        run: yarn run version
      - name: Build & test
        run: | 
          echo "Building and testing..."
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: latest
      #     prerelease: false
      #     files: |
      #       LICENSE.txt
      #       *.jar
      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version
          title: Test PR for Release
          commit: Test commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
