# From https://github.com/changesets/action#example-workflow
name: Release

on:
  push:
    branches:
      - main
      - changesets
  workflow_dispatch:


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: yarn install
    - name: Generate changelogs
      run: yarn run version
    - name: Create Release Pull Request
      uses: changesets/action@master
      with:
        version: yarn version
        title: Test PR for Release
        commit: Test commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Create Release Pull Request
      uses: changesets/action@c3d88279fd9abe11410de073005e34863f735b1c # pin@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
