# From https://github.com/changesets/action#example-workflow
name: Release

on:
  push:
    branches:
      - main
      - changesets
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Generate changelogs
        run: yarn run version
      - name: Build & test
        run: | 
          echo "Building and testing..."
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version
          title: Test PR for Release
          commit: Test commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
