name: Run scheduled jobs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-workflows:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_TOKEN: ${{secrets.OCTOKIT_GITHUB_WORKFLOW_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Run delete workflows script
        uses: ./.github/actions/delete-workflows
        with:
          token: ${{ secrets.OCTOKIT_GITHUB_WORKFLOW_TOKEN }}
  build-devcontainer-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push devcontainer image
        uses: ./.github/actions/build-devcontainer-image
        with:
          token: ${{ secrets.GHA_TOKEN }}
  migrate-dbs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Migrate DBs
        uses: ./.github/actions/migrate-dbs
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          SRC: 'Qa'
          DEST: 'Dev'
