name: Reusable SecRel Flow

on:
  pull_request:
    branches:
      - main
  release:
    types: ['created']
  workflow_dispatch:
    types:
      - secrel-development-complete
      - secrel-release-complete

jobs:
  build-and-scan:
    name: Tornado Pipeline
    uses: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/.github/workflows/pipeline.yml@main
    with:
      config-file: .github/secrel/config.yml
    secrets:
      REPO_SECRETS: ${{ toJson(secrets) }}
