name: techdocs-publish-with-jenkins

on: 
  workflow_dispatch:
    inputs:
      archive_download_url: 
        description: 'archive_download_url'
        required: true
      entity:
        description: 'bucket entity string'
        required: true

jobs:
  run-jenkinsfile:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_DOWNLOAD_URL: ${{ github.event.inputs.archive_download_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHIVE_DOWNLOAD_URL: ${{ env.ARCHIVE_DOWNLOAD_URL }}
          TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENTITY: ${{ github.event.inputs.entity }}
