name: techdocs-run-jenkins

on: workflow_dispatch

jobs:
  run-jenkinsfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '7428-jenkins-test'
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
