name: Unit Tests

# Runs all tests using the `yarn test:all` command.
#
# Tests will be run for all packages along with showing test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test:all
