name: Unit Tests

# Runs all tests using the `yarn test:all` command.
#
# Tests will be run for all packages along with showing test coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      artifact_name: ${{ steps.unit-tests.outputs.artifact_name }}
      matrix: ${{ steps.unit-tests.outputs.matrix_string }}
    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        id: unit-tests
        uses: ./.github/actions/unit-tests

  check-test-coverage:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    strategy:
      matrix:
        packages: ${{ fromJson(needs.unit-tests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Check coverage for ${{ matrix.packages }}
        if: matrix.packages != 'backend'
        uses: ./.github/actions/check-code-coverage
        with:
          artifact_name: ${{ needs.unit-tests.outputs.artifact_name }}
          dir: ${{ matrix.packages }}