name: Unit Tests

# Runs all tests using the `yarn test:all` command.
#
# Tests will be run for all packages along with showing test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run:
          yarn install
      - name: Test
        run: yarn test:all
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./logs

  check-test-coverage:
    runs-on: ubuntu-latest
    needs: run-all-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/download-artifact@v2
        with:
          name: logs
          path: ./logs
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./logs/coverage/lcov.info"
          min_coverage: 0
          exclude: "node_modules"
          
          
